const fs = require('node:fs');
const pages = JSON.parse(fs.readFileSync('content/pages.json','utf8'));
const esc = value => String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const shell = (title,body) => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | UZMA Geospatial AI</title><link rel="icon" href="../assets/img/brand/favicon.png"><link rel="stylesheet" href="../assets/css/content.css"></head><body><a class="skip" href="#main">Skip to content</a><header><a href="../index.html"><span class="brand-pair"><img class="uzma-mark" src="../assets/img/brand/uzma-group.png" width="1156" height="264" alt="UZMA"><span class="brand-divider" aria-hidden="true"></span><img class="geoai-mark" src="../assets/library/Logo-GeoAI_300px.png" width="300" height="65" alt="Geospatial AI, an Uzma company"></span></a><nav aria-label="Main navigation"><a href="../index.html#uzmasat">UZMASAT-1</a><a href="../index.html#solutions">Solutions</a><a href="index.html">Explore</a><a href="../index.html#contact">Contact</a></nav></header><main id="main">${body}</main><footer><span class="brand-pair"><img class="uzma-mark" src="../assets/img/brand/uzma-group.png" width="1156" height="264" alt="UZMA"><span class="brand-divider" aria-hidden="true"></span><img class="geoai-mark" src="../assets/library/Logo-GeoAI_300px.png" width="300" height="65" alt="Geospatial AI, an Uzma company"></span><p>See better. See the bigger picture. See the unseen.</p><a href="../index.html">Back to the homepage ↗</a><p>© 2026 Geospatial AI Sdn Bhd.</p></footer></body></html>`;
fs.mkdirSync('redesign/content',{recursive:true});
for (const p of pages) {
 const related=pages.filter(x=>x.category===p.category && x.slug!==p.slug).slice(0,3);
 fs.writeFileSync(`redesign/content/${p.slug}.html`,shell(p.title,`<div class="article-heading"><a class="back" href="index.html">← Explore our world</a><p class="eyebrow">${esc(p.category)}</p><h1>${esc(p.title)}</h1><p class="reading-time">${Math.max(1,Math.ceil(p.words/180))} min read</p></div><article class="article-body">${p.html}</article><aside class="related"><h2>Keep exploring</h2><div class="cards">${related.map(card).join('')}</div></aside>`));
}
function card(p) {const img=p.media.find(x=>/\.(jpg|jpeg|webp|png)$/i.test(x));return `<a class="card" href="${p.slug}.html">${img?`<img src="${esc(img)}" alt="" loading="lazy">`:'<div class="card-art" aria-hidden="true">↗</div>'}<div><p class="eyebrow">${esc(p.category)}</p><h3>${esc(p.title)}</h3><span>Explore ↗</span></div></a>`;}
fs.writeFileSync('redesign/content/index.html',shell('Explore our world',`<div class="library-heading"><p class="eyebrow">Ideas. Expertise. Perspective.</p><h1>A closer look.<br><span>A wider perspective.</span></h1><p>Discover our capabilities, meet the company and follow the journey of UZMASAT-1.</p><nav class="topics" aria-label="Content categories"><a href="#company">Company</a><a href="#capabilities">Capabilities</a><a href="#news">News & insights</a></nav></div>${[['Company','company'],['Capabilities','capabilities'],['News & insights','news']].map(([category,id])=>`<section class="library-section" id="${id}"><div class="section-heading"><h2>${esc(category)}</h2><span>${pages.filter(p=>p.category===category).length} stories</span></div><div class="cards">${pages.filter(p=>p.category===category).map(card).join('')}</div></section>`).join('')}`));
console.log(`Built ${pages.length} content pages and the library index.`);
